### ISSUE TITLE
Superscript appears as normal text

### ISSUE THREAD

**Issue by mkamener** [reasonml/reasonml.github.io#433]
e.g. on https://reasonml.github.io/api/Random.html, 2<sup>30</sup> appears as 230.

This seems to be due to using a CSS reset without then adding back style for the `sup` element.

A style like this should be added:

```css
sup {
    vertical-align: super;
    font-size: 80%;
}
```
